### PR TITLE
exporting EmailException

### PR DESCRIPTION
**Pull request by cesar3030**
EmailException class was exported in the TS file but not in the JS file so it was not possible to do such thing: 
```javascript
if (err instanceof EmailException) {
 ...
}
```

### CODE REVIEW

**Comment by tschoffelen** [comment]
Oh, good point. Do we need to add the same for the `index.android.js` file?

**Comment by cesar3030** [comment]
I'll do some tests next week and comeback to you regarding if we need to add it to index.android.js

**Comment by cesar3030** [comment]
I created a new class in a `src` folder that holds the code of EmailException to avoid having to redefine it in `android.index.js`. I import and export`EmailException` in both index files to be able to use it in the index file but also to make it available to developers who wants to use it in there code to do a `if (err instanceof EmailException) { ... }` 

Tell me if you prefer not to have a `src/` and have the `email-exception.js` file in the root folder.

**Comment by tschoffelen** [comment]
Looks great!

**Comment by tschoffelen** [comment]
Released as `react-native-email-link@1.6.4`.

**Pull request merged**
